# Generated by Django 5.0.7 on 2024-07-28 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bid_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wishlistedBy',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
