# Generated by Django 5.0.7 on 2024-07-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
