# Generated by Django 5.0.7 on 2024-07-29 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='wishlistedBy',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
